{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastshap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastshap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastshap/fastshap_{{ version }}.tar.gz
  sha256: 861d38f1f7ccdaa1604f98ca24b580a2d3ac8e5278e4fd6e61df675550615084

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.1
    - r-rcpparmadillo
    - r-foreach
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.1
    - r-rcpparmadillo
    - r-foreach

test:
  commands:
    - $R -e "library('fastshap')"           # [not win]
    - "\"%R%\" -e \"library('fastshap')\""  # [win]

about:
  home: https://bgreenwell.github.io/fastshap/
  dev_url: https://github.com/bgreenwell/fastshap
  license: GPL-2.0-or-later
  summary: Computes fast (relative to other implementations) approximate Shapley values for any
    supervised learning model. Shapley values help to explain the predictions from any
    black box model using ideas from game theory; see Strumbel and Kononenko (2014)
    <doi:10.1007/s10115-013-0679-x> for details.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - apeltzer
    - SMLMS
    - neslihanky
    - KaBrrrp

# Package: fastshap
# Type: Package
# Title: Fast Approximate Shapley Values
# Version: 0.1.0
# Authors@R: person("Brandon", "Greenwell", email = "greenwell.brandon@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8120-0084"))
# Description: Computes fast (relative to other implementations) approximate Shapley values for any supervised learning model. Shapley values help to explain the predictions from any black box model using ideas from game theory; see Strumbel and Kononenko (2014) <doi:10.1007/s10115-013-0679-x> for details.
# License: GPL (>= 2)
# URL: https://github.com/bgreenwell/fastshap, https://bgreenwell.github.io/fastshap/
# BugReports: https://github.com/bgreenwell/fastshap/issues
# Imports: foreach, Rcpp (>= 1.0.1), utils
# Enhances: lightgbm, xgboost
# Suggests: AmesHousing, covr, knitr, ranger, rmarkdown, shapviz (>= 0.8.0), tibble, tinytest (>= 1.4.1)
# LinkingTo: Rcpp, RcppArmadillo
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# Depends: R (>= 3.6.0)
# LazyData: true
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2023-05-10 23:50:25 UTC; bgreenwell
# Author: Brandon Greenwell [aut, cre] (<https://orcid.org/0000-0002-8120-0084>)
# Maintainer: Brandon Greenwell <greenwell.brandon@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-06-06 09:20:02 UTC
